### ISSUE TITLE
Testing groups of variables

### ISSUE THREAD

**Issue by variani** [davidruegamer/coinflibs#2]
Hi,

Thank you for the package and nice preprint explaining the details.

I am curious whether there is a function or code example for Section 2.3 "Testing groups of variables" in your [preprint](https://arxiv.org/abs/1706.09796). Any tips?

I can see functions to get p-values for single variables in [p-value_calculation.R](https://github.com/davidruegamer/coinflibs/blob/master/R/p-value_calculation.R). But my use case is about tests for groups of variables after variable selection. It would be great to get you feedback.

Best,
Andrey

**Comment by davidruegamer** [comment]
Hi Andrey,

thanks for noting. I will add the functionality as soon as possible and let you know when I'm done!

Best,
David

**Comment by davidruegamer** [comment]
Hi Andrey,

sorry for the super late response. I finally had time to look into my code and it seems that I have already implemented this - at least for factor variables. For example, 

```r
library(MASS)
data("cpus")
# Fit initial model
cpus$perf <- log10(cpus$perf)
# the following is a factor variabe
cpus$cach <- as.factor(cpus$cach)
mod <- lm(perf ~ .-name, data = cpus)

# use the stepAIC function to find the best model in a backward 
# stepwise search
cpus.lm <- stepAIC(mod, trace = FALSE, direction = "backward", steps = 3)
# check model selection
cpus.lm$anova$Step

# recalculate all visited models in the first step
lom1 <- c(lapply(attr(mod$terms, "term.labels"), function(x) 
update(mod, as.formula(paste0("perf ~ .-", x)))), list(mod))

# perform likelihood ratio test at level 
alpha = 0.001

# check for non-significant variables
coefTable <- anova(cpus.lm)
drop <- rownames(coefTable)[alpha < coefTable[-nrow(coefTable),5]]

# drop non-significant variable
cpus.lm2 <- update(cpus.lm, as.formula(paste0(".~.-",drop)))

# compute selective inference
selinf(list(cpus.lm, cpus.lm2), lom1, response = cpus$perf, 
what = c("Ftest", "aic"), sd = summary(cpus.lm2)$sigma)
```
will give you also the p-value for the variable `cach`. The calculation of the factor variable is triggered [here](https://github.com/davidruegamer/coinflibs/blob/master/R/selinf.R#L225) and then calculated with the truncated chi-distribution [here](https://github.com/davidruegamer/coinflibs/blob/5a7a3d2613b28734c3cdca85a97f04cc8bd1858b/R/selectiveInference_functions.R#L5).

Or did you have other types of grouped variables in mind?

Best,
David

**Comment by variani** [comment]
HI David,

You response is fast indeed, given you touched your package last time three years ago. It's nice you pointed me to specific lines of code and clarified with the example with factor variables.

My use case is testing for association a group of continuous variables after model selection, and I think I can adopt your code.

As a side question. Is that right that your package is for modeling quantitative response only? Or do I miss something? I know the selectiveInference package allows for post-selection inference in generalized models.

Thank you.

Best,
Andrey

**Comment by davidruegamer** [comment]
Hi Andrey,

yes, you are correct. The "package" only provides selective inference in case of a normal distribution assumption of the response. The idea (of the paper and the package) was to provide inference results in cases where the exact truncation of the distribution by the selection procedure is known. At the time where I did this, there was no generalized solution available. Also from what I've read so far, the inference statements for non-normal response variables are only approximate ones. But I will sooner or later have to look into this / read up on the latest developments and maybe then update this package accordingly.

If you need help with the test for a group of continuous variables, let me know.

Best,
David

**Comment by variani** [comment]
For now working with normal responses is enough to me for experimenting, but I wish to cover logistic models at some point in the future. I will keep you posted if there is any issue, and thank you again for the comments.
